#!/bin/sh

set -x 
set -euo pipefail

# TODO: unpack python

# link src, to make orgs happy
ln -s production src

# run tests to generate C++ bindings
cd production && $HOME/python_tbd/bin/python -m pytest
