#!/bin/bash

set -x 
set -euo pipefail

# unpack python

tar -xaf tbd_python.tar.xz

# link src, to make orgs happy
ln -s production src || true

# run tests to generate C++ bindings
cd production && TBD_RELEASE=yes $HOME/tbd_python/bin/python3.6 -m pytest
